apiVersion: batch/v1
kind: Job

metadata:
  name: case-study7-job

spec:
  backoffLimit: 2

  template:
    metadata:
      labels:
        app: case-study7

    spec:
      restartPolicy: Never

      containers:
      - name: case-study7

        image: archie650/case-study7:latest
        imagePullPolicy: Always

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"

          limits:
            cpu: "1"
            memory: "2Gi"
