apiVersion: apps/v1
kind: Deployment

metadata:
  name: case-study7

spec:
  replicas: 1

  selector:
    matchLabels:
      app: case-study7

  template:
    metadata:
      labels:
        app: case-study7

    spec:
      containers:
      - name: case-study7
        image: archie650/case-study7:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 4040

        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"

---
apiVersion: v1
kind: Service

metadata:
  name: case-study7-service

spec:
  selector:
    app: case-study7

  ports:
  - protocol: TCP
    port: 4040
    targetPort: 4040

  type: NodePort
