apiVersion: apps/v1
kind: Deployment

metadata:
  name: case-study7
  labels:
    app: case-study7

spec:
  replicas: 1

  selector:
    matchLabels:
      app: case-study7

  template:
    metadata:
      labels:
        app: case-study7

    spec:
      containers:
        - name: case-study7
          image: archie650/case-study7:v2
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4040

          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "2Gi"