apiVersion: apps/v1
kind: Deployment

metadata:
  name: smart-energy-insights

spec:
  replicas: 1

  selector:
    matchLabels:
      app: smart-energy-insights

  template:
    metadata:
      labels:
        app: smart-energy-insights

    spec:
      containers:
      - name: smart-energy-insights
        image: archie650/smart-energy-insights:latest
        imagePullPolicy: Always

        ports:
        - containerPort: 8501